dist: bionic
language: bash
sudo: required
services: [docker]

script:
  - docker run --network=host -v $(pwd):$(pwd) -w $(pwd) snapcore/snapcraft:beta sh -c "apt update && snapcraft"
  - sudo apt update
  - sudo snap install core --edge
  - sudo snap set core experimental.layouts=true
  - sudo snap install *.snap --dangerous
  - for i in docker-privileged k8s-kubelet kernel-module-observe network-bind network  k8s-kubeproxy network-observe dot-kube docker-support firewall-control hardware-observe kernel-module-control mount-observe network-control process-control system-observe; do sudo snap connect microk8s:$i; done
  - sudo snap stop microk8s
  - sudo snap start microk8s
  - sleep 30; sudo journalctl -u snap.microk8s.daemon-containerd
  - sudo pip install -U pytest
  - pwd
  - ps -ef
  - ls -l
  - ./tests/smoke-test.sh
  - export UNDER_TIME_PRESURE="True"
  - (cd tests; pytest -s verify-branches.py)
  - (cd tests; sudo pytest -s test-addons.py)
  - sudo microk8s.reset
  - sudo snap remove microk8s
  - sudo UPGRADE_MICROK8S_FROM=edge UPGRADE_MICROK8S_TO=`pwd`/`ls microk8s*.snap` pytest -s ./tests/test-upgrade.py
